name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2.0.0
        with:
          version: 25.10.0
      
      - name: Setup nf-test
        uses: nf-core/setup-nf-test@v1.3.6
        with:
          version: 0.9.2

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.4.4

      - name: Run nf-test
        run: nf-test test main.nf.test
